/**
 * Mapping des mots-cles vers les articles du CGI 2026
 * Chapitre IS - Impot sur les Societes (Art. 1 a 92K)
 *
 * REGLE : Le premier article de chaque liste est la SOURCE PRIMAIRE
 *
 * @author NORMX AI - CGI 242
 * @version 2026
 * @base Directive CEMAC n0119/25-UEAC-177-CM-42 du 09 janvier 2025
 */

export const KEYWORD_ARTICLE_MAP_2026: Record<string, string[]> = {

  // ========== GENERALITES - TAUX IS ==========

  // ========== ART. 2 - PERSONNES IMPOSABLES ==========
  'personnes imposables is': ['Art. 2'],
  'societes de capitaux': ['Art. 2'],
  'sa': ['Art. 2'],
  'sas': ['Art. 2'],
  'sarl': ['Art. 2'],
  'option is': ['Art. 2'],
  'snc option': ['Art. 2'],
  '30 octobre': ['Art. 2'],

  // ========== ART. 3 - EXONERATIONS ==========
  'exonerations is': ['Art. 3'],
  'exonération is': ['Art. 3'],
  'exonérations is': ['Art. 3'],
  'exoneration is': ['Art. 3'],
  "exonération de l'is": ['Art. 3'],
  "exoneration de l'is": ['Art. 3'],
  "exonérations de l'is": ['Art. 3'],
  "exonerations de l'is": ['Art. 3'],
  'exonérées is': ['Art. 3'],
  'exonerees is': ['Art. 3'],
  "exonérées de l'is": ['Art. 3'],
  "exonerees de l'is": ['Art. 3'],
  "exonérées de l'impôt sur les sociétés": ['Art. 3'],
  "exonerees de l'impot sur les societes": ['Art. 3'],
  'cooperatives agricoles': ['Art. 3'],
  'exonerations conventionnelles': ['Art. 3'],
  'exonérations conventionnelles': ['Art. 3'],
  'suppression exonerations': ['Art. 3'],

  // ========== ART. 3A - CREDIT D'IMPOT ==========

  // ========== ART. 4, 4A, 7 - TERRITORIALITE ==========
  'territorialite is': ['Art. 4'],
  'residence fiscale societe': ['Art. 7'],

  // ========== ART. 8-11 - BENEFICE IMPOSABLE ==========
  'benefice imposable': ['Art. 8'],
  'benefice net': ['Art. 8'],
  'actif net': ['Art. 9'],
  'stocks': ['Art. 10'],
  'periode imposition': ['Art. 11'],

  // ========== ART. 12-16 - PRODUITS IMPOSABLES ==========
  'produits imposables': ['Art. 12'],
  'revenus etrangers': ['Art. 13'],
  'cessions actif': ['Art. 14', 'Art. 15', 'Art. 16'],

  // ========== ART. 17-25 - PLUS-VALUES ==========
  'plus-values': ['Art. 17'],
  'moins-values': ['Art. 17'],
  'regime plus-values': ['Art. 17'],
  'regime mere-fille': ['Art. 20', 'Art. 21'],
  'dividendes intragroupe': ['Art. 20'],
  'restructurations': ['Art. 22', 'Art. 23', 'Art. 24', 'Art. 25'],
  'fusion': ['Art. 22'],
  'scission': ['Art. 23'],
  'apport partiel actif': ['Art. 24'],

  // ========== ART. 26 - CONDITIONS DEDUCTIBILITE ==========
  'conditions deductibilite': ['Art. 26'],
  'charges deductibles': ['Art. 26'],
  'acte anormal gestion': ['Art. 26'],
  '200 000 fcfa': ['Art. 26'],
  '200000 fcfa': ['Art. 26'],
  '200.000 fcfa': ['Art. 26'],
  'deux cent mille': ['Art. 26'],
  'paiement especes': ['Art. 26'],
  'especes': ['Art. 26'],
  'cash': ['Art. 26'],
  'numeraire': ['Art. 26'],
  'liquide': ['Art. 26'],
  'argent liquide': ['Art. 26'],
  'plafond especes': ['Art. 26'],
  'reglement especes': ['Art. 26'],
  'montant maximum especes': ['Art. 26'],
  'seuil especes': ['Art. 26'],

  // ========== ART. 27-37 - CHARGES PERSONNEL ==========
  'charges personnel': ['Art. 27'],
  'remunerations': ['Art. 27'],
  'salaires deductibles': ['Art. 27'],
  'gerants': ['Art. 28', 'Art. 29'],
  'administrateurs': ['Art. 30', 'Art. 31', 'Art. 32'],
  'jetons presence': ['Art. 30'],
  'frais transport': ['Art. 35', 'Art. 36'],
  'voyages conges': ['Art. 37'],

  // ========== ART. 38-41 - FRAIS SIEGE REDEVANCES ==========
  'frais de siege': ['Art. 38'],
  'redevances': ['Art. 39', 'Art. 40'],
  'commissions': ['Art. 39'],
  '20% redevances': ['Art. 39'],
  'pret main oeuvre': ['Art. 41'],

  // ========== ART. 42 - LOYERS ==========
  'loyers': ['Art. 42'],
  'credit-bail': ['Art. 42', 'Art. 55', 'Art. 56'],
  'leasing': ['Art. 42', 'Art. 55'],

  // ========== ART. 43 - IMPOTS DEDUCTIBLES ==========
  'impots deductibles': ['Art. 43'],
  'amendes non deductibles': ['Art. 43'],

  // ========== ART. 44 - ASSURANCES ==========
  'assurances deductibles': ['Art. 44'],
  'primes assurance': ['Art. 44'],
  'captives assurance': ['Art. 44'],

  // ========== ART. 45-46 - DONS LIBERALITES ==========
  'dons': ['Art. 45'],
  'liberalites': ['Art. 45'],
  'subventions': ['Art. 45'],
  'aides non deductibles': ['Art. 46'],
  'sfec': ['Art. 46', 'Art. 61'],

  // ========== ART. 47 - DEPENSES SOMPTUAIRES ==========
  'depenses somptuaires': ['Art. 47'],
  'chasse': ['Art. 47'],
  'plaisance': ['Art. 47'],

  // ========== ART. 48 - REMUNERATIONS OCCULTES ==========
  'remunerations occultes': ['Art. 48'],

  // ========== ART. 49 - CHARGES FINANCIERES ==========
  'charges financieres': ['Art. 49'],
  'interets': ['Art. 49'],
  'sous-capitalisation': ['Art. 49'],
  '20% ebe': ['Art. 49'],
  'limitation interets': ['Art. 49'],
  'beac': ['Art. 49'],

  // ========== ART. 51-61 - AMORTISSEMENTS ==========
  'amortissements': ['Art. 51'],
  'taux amortissement': ['Art. 52'],
  'amortissement lineaire': ['Art. 53'],
  'amortissement degressif': ['Art. 54'],
  'amortissement accelere': ['Art. 57'],
  '40 000 000 fcfa': ['Art. 57', 'Art. 58'],
  'vehicules tourisme': ['Art. 58'],
  '500 000 fcfa': ['Art. 59'],
  'amortissement 100%': ['Art. 59', 'Art. 61'],

  // ========== ART. 63-74 - PROVISIONS ==========
  'provisions': ['Art. 63'],
  'creances douteuses': ['Art. 64'],
  'provision stock': ['Art. 65'],
  'cobac': ['Art. 66'],
  'provisions reglementees': ['Art. 67'],

  // ========== ART. 75 - REPORT DEFICITS ==========
  'report deficits': ['Art. 75'],
  'deficits reportables': ['Art. 75'],
  '5 ans deficit': ['Art. 75'],
  'pertes reportables': ['Art. 75'],

  // ========== ART. 77-85 - PRIX DE TRANSFERT ==========
  'prix de transfert': ['Art. 77'],
  'prix transfert': ['Art. 77'],
  'parties liees': ['Art. 77'],
  'entreprises liees': ['Art. 77'],
  'documentation prix transfert': ['Art. 78'],
  '500 000 000 fcfa': ['Art. 78'],
  'methodes prix transfert': ['Art. 79'],
  'cup': ['Art. 79'],
  'mtmn': ['Art. 79'],
  'app': ['Art. 80'],
  'accord prealable prix': ['Art. 80'],
  'sanctions prix transfert': ['Art. 81'],
  '5 000 000 amende': ['Art. 81'],
  '25 000 000 amende': ['Art. 81'],
  'declaration pays par pays': ['Art. 82', 'Art. 83', 'Art. 84', 'Art. 85'],

  // ========== ART. 86-86F - ASSIETTE, TAUX ET RETENUES ==========
  'assiette is': ['Art. 86'],
  'acomptes is': ['Art. 124'],
  '15 fevrier': ['Art. 124'],
  '15 mai': ['Art. 124'],
  '15 aout': ['Art. 124'],
  '15 novembre': ['Art. 124'],

  // ========== ART. 87 - REGIME MERE-FILLE ==========
  'societes meres': ['Art. 87'],
  'filiales': ['Art. 87'],
  'dividendes mere-fille': ['Art. 87'],
  '25% participation': ['Art. 87'],

  // ========== ART. 88 - SUCCURSALES ==========
  'succursales': ['Art. 88'],
  'conventions internationales': ['Art. 88'],

  // ========== ART. 89 - QUARTIERS GENERAUX ==========
  'quartiers generaux': ['Art. 89'],
  'qg cemac': ['Art. 89'],

  // ========== ART. 90 - HOLDINGS ==========
  'holdings': ['Art. 90'],
  'societe holding': ['Art. 90'],
  'deux tiers actif': ['Art. 90'],

  // ========== ART. 91 - INTEGRATION FISCALE ==========
  'integration fiscale': ['Art. 91'],
  'groupe fiscal': ['Art. 91'],
  '95% participation': ['Art. 91'],

  // ========== ART. 92 - PERSONNES MORALES ETRANGERES ==========
  'personnes morales etrangeres': ['Art. 92'],
  'non residents is': ['Art. 92'],
  'forfaitaire 22%': ['Art. 92'],

  // ========== ART. 92A - BASE FORFAITAIRE ETRANGERS ==========
  // 'mob' et 'demob' supprimés - causent des faux positifs (ex: "immobilières" contient "mob")

  // ========== ART. 92J - REGIME DEROGATOIRE PETROLIER ==========
  'charte investissements': ['Art. 3'],
  'charte des investissements': ['Art. 3'],

  // ========== ART. 185 ter - IRCM DIVIDENDES ==========

  // ========== ART. 378 - SANCTIONS ==========
  'sanctions fiscales': ['Art. 378', 'Art. 81'],
  'penalites fiscales': ['Art. 378'],
  'amendes fiscales': ['Art. 378', 'Art. 81'],
  'interet retard': ['Art. 378'],
  'majoration retard': ['Art. 378'],

  // ========== IRF - IMPOT SUR LE REVENU FONCIER (Art. 111-113A) ==========
  // Art. 111 - Champ d'application IRF
  'irf': ['Art. 111'],
  'revenus fonciers': ['Art. 111'],
  'loyers imposables': ['Art. 111'],
  'proprietes baties': ['Art. 111'],
  'proprietes non baties': ['Art. 111'],
  'impot revenu foncier': ['Art. 111'],

  // Art. 111B - Crédit-bail immobilier IRF

  // Art. 111C - Exonérations IRF

  // Art. 113 - Taux IRF
  'taux irf': ['Art. 113'],
  'taux loyers': ['Art. 113'],
  'taux revenus fonciers': ['Art. 113'],
  '9%': ['Art. 113'],
  '9 pour cent': ['Art. 113'],
  'taux plus-values immobilieres': ['Art. 113'],
  'taux plus-values immobilières': ['Art. 113'],
  'plus-values immobilières': ['Art. 113'],
  'taux irf plus-values': ['Art. 113'],
  '15% plus-values': ['Art. 113'],
  '15% immobilier': ['Art. 113'],
  'quinze pour cent plus-values': ['Art. 113'],
  'taux plus-value immobiliere': ['Art. 113'],
  'taux plus-value immobilière': ['Art. 113'],
  'plus-values immobilieres taux': ['Art. 113'],
  'irf sur les plus-values': ['Art. 113'],
  'sur les plus-values immobilieres': ['Art. 113'],
  'sur les plus-values immobilières': ['Art. 113'],
  'plus-values immobili': ['Art. 113'],

  // Art. 113A - Retenue à la source IRF

  // ======================================================================================
  // KEYWORDS MIGRÉS DEPUIS CGI 2025 (anciens numéros d'articles, toujours dans Qdrant)
  // ======================================================================================

  // ========== IRPP - CATÉGORIES DE REVENUS (Art. 1-101 ancien) ==========
  'catégories de revenus': ['Art. 1'],
  'catégories revenus': ['Art. 1'],
  'sept catégories': ['Art. 1'],
  '7 catégories': ['Art. 1'],
  'composition du revenu': ['Art. 1'],
  'quelles catégories': ['Art. 1'],
  'revenu net global': ['Art. 1', 'Art. 11', 'Art. 66'],

  // ART. 2 - PERSONNES IMPOSABLES IRPP
  'personnes imposables': ['Art. 2'],
  'qui est imposable': ['Art. 2'],
  'domicile fiscal': ['Art. 2', 'Art. 8'],
  'résidence habituelle': ['Art. 2'],
  'résidence fiscale': ['Art. 2'],
  'vingt-quatre mois': ['Art. 2'],
  '24 mois': ['Art. 2'],
  'perte de résidence': ['Art. 2'],
  'durée absence': ['Art. 2'],
  'absence continue': ['Art. 2'],

  // ART. 3 - EXONÉRATIONS IRPP
  'exonération irpp': ['Art. 3', 'Art. 38'],
  'affranchis de l\'impôt': ['Art. 3'],
  'qui est exonéré': ['Art. 3'],
  'minimum imposable': ['Art. 3', 'Art. 95'],
  'diplomates': ['Art. 3'],

  // ART. 4 - FOYER FISCAL
  'chef de famille': ['Art. 4'],
  'foyer fiscal': ['Art. 4', 'Art. 91'],
  'imposition distincte': ['Art. 4'],
  'femme mariée': ['Art. 4'],
  'enfants à charge': ['Art. 93', 'Art. 91', 'Art. 4'],

  // ART. 6 - ASSOCIÉS
  'associés': ['Art. 6'],
  'sociétés de personnes': ['Art. 6'],
  'snc': ['Art. 6'],
  'gie': ['Art. 6'],

  // ART. 8 - LIEU D'IMPOSITION
  'lieu d\'imposition': ['Art. 8'],
  'lieu imposition': ['Art. 8'],

  // ART. 12-13 - REVENUS FONCIERS (ancien)
  'propriétés bâties': ['Art. 12'],
  'location': ['Art. 12'],
  'loyer': ['Art. 12'],
  'revenu net foncier': ['Art. 13'],

  // ART. 14-15 - BICA
  'bica': ['Art. 14'],
  'bénéfices industriels': ['Art. 14', 'Art. 1'],
  'bénéfices commerciaux': ['Art. 14', 'Art. 1'],
  'bénéfices artisanaux': ['Art. 14'],
  'location meublée': ['Art. 15'],
  'fonds de commerce': ['Art. 15', 'Art. 63'],

  // ART. 15 bis - DÉCLARATION D'EXISTENCE

  // ART. 26, 28 - RÉGIME DU FORFAIT (ancien)
  'régime du forfait': ['Art. 26'],
  '100 000 000': ['Art. 26', 'Art. 30'],
  '100 millions': ['Art. 26', 'Art. 30'],
  'seuil forfait': ['Art. 26'],
  'exclusions forfait': ['Art. 26'],
  'déclaration 294': ['Art. 26', 'Art. 28'],
  'déclaration n°294': ['Art. 26', 'Art. 28'],
  'déclaration no 294': ['Art. 26', 'Art. 28'],
  'formulaire 294': ['Art. 26', 'Art. 28'],
  'imprimé 294': ['Art. 26', 'Art. 28'],
  '294': ['Art. 26', 'Art. 28'],
  'déclaration forfait contenu': ['Art. 28', 'Art. 26'],
  'états financiers forfait': ['Art. 28', 'Art. 26'],
  'déclaration spéciale forfait': ['Art. 28'],

  // ART. 30 - RÉGIME DU RÉEL (ancien)
  'régime du réel': ['Art. 30'],
  'régime réel': ['Art. 30'],
  'bénéfice réel': ['Art. 30', 'Art. 17'],
  '2 milliards': ['Art. 30'],
  'grandes entreprises': ['Art. 30'],

  // ART. 31 - ÉTATS FINANCIERS (ancien)
  'états financiers': ['Art. 31'],
  'dsf': ['Art. 31'],
  'ohada': ['Art. 31', 'Art. 28'],
  'bilan': ['Art. 31'],
  'compte de résultat': ['Art. 31'],

  // ART. 33 - RECTIFICATION D'OFFICE
  'rectification d\'office': ['Art. 33'],
  'rectification office': ['Art. 33'],
  'rectifier d\'office': ['Art. 33'],
  'documents comptables insuffisants': ['Art. 33'],
  'livres registres insuffisants': ['Art. 33'],
  'résultats imprécis': ['Art. 33'],
  'procéder rectification': ['Art. 33'],

  // ART. 86 - TAXATION D'OFFICE
  'taxation d\'office': ['Art. 86', 'Art. 33'],
  'mise en demeure': ['Art. 86', 'Art. 33'],

  // ART. 36 - BÉNÉFICES AGRICOLES
  'bénéfices agricoles': ['Art. 1'],

  // ART. 37-41 - TRAITEMENTS ET SALAIRES (ancien)
  'traitements salaires': ['Art. 37', 'Art. 1'],
  'traitements et salaires': ['Art. 37', 'Art. 1'],
  'rentes viagères': ['Art. 37', 'Art. 38'],

  // ART. 38 - EXONÉRATIONS SALAIRES
  'exonérations salaires': ['Art. 38'],
  'allocations familiales': ['Art. 38'],
  'indemnité licenciement': ['Art. 38'],
  'pension retraite': ['Art. 38'],

  // ART. 39 - AVANTAGES EN NATURE (ancien)
  'voiture': ['Art. 39'],

  // ART. 41 - DÉDUCTION 20%
  'déduction forfaitaire 20%': ['Art. 41'],
  'abattement 20%': ['Art. 41'],

  // ART. 42-43 - BNC (ancien)
  'professions non commerciales': ['Art. 42', 'Art. 1'],
  'droits d\'auteur': ['Art. 42'],
  'honoraires': ['Art. 42'],

  // ART. 49 - ARTISTES NON-RÉSIDENTS
  'artiste étranger': ['Art. 49', 'Art. 185 ter-A'],
  'artiste non résident': ['Art. 49', 'Art. 185 ter-A'],
  'artiste non-résident': ['Art. 49', 'Art. 185 ter-A'],
  'artiste non domicilié': ['Art. 49', 'Art. 185 ter-A'],
  'musicien étranger': ['Art. 49', 'Art. 185 ter-A'],
  'musicien non résident': ['Art. 49', 'Art. 185 ter-A'],
  'concert artiste étranger': ['Art. 49', 'Art. 185 ter-A'],
  'spectacle artiste étranger': ['Art. 49', 'Art. 185 ter-A'],
  'représentation artistique': ['Art. 49'],
  'cachets artistes': ['Art. 49', 'Art. 96'],
  'artiste organise concert': ['Art. 49'],
  'artiste organise spectacle': ['Art. 49'],
  'représentant légal artiste': ['Art. 49'],
  'music-hall': ['Art. 49'],
  'théâtre artiste': ['Art. 49'],

  // ART. 50-62 - CAPITAUX MOBILIERS (ancien)
  'revenus des capitaux mobiliers': ['Art. 50', 'Art. 1'],
  'capitaux mobiliers': ['Art. 50', 'Art. 1'],
  'tantièmes': ['Art. 57'],
  'jetons de présence': ['Art. 57'],
  'intérêts': ['Art. 58', 'Art. 61'],
  'créances': ['Art. 61'],
  'dépôts': ['Art. 61'],
  'livrets épargne': ['Art. 62'],

  // ART. 63 - PLUS-VALUES (ancien)
  'plus-values cession': ['Art. 63'],
  'cession actif': ['Art. 63'],

  // ART. 66 - CHARGES DÉDUCTIBLES (ancien)
  'déficits': ['Art. 66'],
  'report déficit': ['Art. 66'],
  'pensions alimentaires': ['Art. 66'],
  'intérêts emprunts': ['Art. 66'],
  'assurance vie': ['Art. 66'],
  'honoraires médicaux': ['Art. 66'],

  // ART. 75 - DÉPART DU CONGO
  'départ du congo': ['Art. 75'],
  'transfert domicile': ['Art. 75'],
  'visa de départ': ['Art. 75'],
  'quitter le congo': ['Art. 75'],

  // ART. 76-80 - DÉCLARATIONS (ancien)
  'déclaration revenus': ['Art. 76', 'Art. 80'],
  'obligation déclaration': ['Art. 76'],
  'train de vie': ['Art. 76'],
  'délai déclaration': ['Art. 80'],
  '20 mars': ['Art. 80'],

  // ART. 89 - CALCUL IRPP
  'calcul irpp': ['Art. 89'],
  'mécanisme calcul': ['Art. 89'],

  // ART. 91 - QUOTIENT FAMILIAL (ancien)
  'nombre de parts': ['Art. 91'],
  'parts fiscales': ['Art. 91'],
  'combien de parts': ['Art. 91'],
  'célibataire': ['Art. 91'],
  'marié': ['Art. 91'],
  'divorcé': ['Art. 91'],
  'veuf': ['Art. 91'],
  'demi-part': ['Art. 91'],

  // ART. 93 - ENFANTS À CHARGE (ancien)
  'personnes à charge': ['Art. 93'],
  'enfants légitimes': ['Art. 93'],
  'enfants adoptés': ['Art. 93'],
  '21 ans': ['Art. 93'],
  '25 ans': ['Art. 93'],

  // ART. 95 - BARÈME IRPP (ancien)
  'barème irpp': ['Art. 95'],
  'barème': ['Art. 95'],
  'taux irpp': ['Art. 95'],
  'tranches': ['Art. 95'],
  'tranches irpp': ['Art. 95'],
  '1%': ['Art. 95'],
  '10%': ['Art. 95'],
  '25%': ['Art. 95'],
  '40%': ['Art. 95'],
  '464 000': ['Art. 95'],
  '1 000 000': ['Art. 95'],
  '3 000 000': ['Art. 95'],
  'salaire minimum': ['Art. 95'],

  // ART. 96 - RETENUE À LA SOURCE (ancien)
  'retenue à la source': ['Art. 96'],
  'retenue source 20%': ['Art. 96'],

  // ART. 98-101 - CESSION, CESSATION, DÉCÈS (ancien)
  'cessation': ['Art. 99'],
  'décès exploitant': ['Art. 101'],
  'cessation bnc': ['Art. 99'],
  'imposition décès': ['Art. 101'],

  // COMPLÉMENTS IRPP
  'contribuables exclus': ['Art. 26'],
  'ne peuvent pas bénéficier forfait': ['Art. 26'],
  'hors champ forfait': ['Art. 26'],
  'amende registres': ['Art. 28'],
  'défaut tenue registres': ['Art. 28'],
  'conservation documents': ['Art. 31'],
  'durée conservation': ['Art. 31'],
  'dix ans': ['Art. 31'],
  '10 ans': ['Art. 31'],
  'allocations familiales employeur': ['Art. 38'],
  '5 000 fcfa enfant': ['Art. 38'],
  'maximum parts': ['Art. 91'],
  '6,5 parts': ['Art. 91'],
  'plafond parts': ['Art. 91'],
  'trente jours': ['Art. 75'],
  '30 jours': ['Art. 75'],
  'veuf parts': ['Art. 91'],
  'deux années': ['Art. 91'],
  'revenus exceptionnels': ['Art. 71'],
  'étalement': ['Art. 71'],
  'système du quotient': ['Art. 71'],
  'ayants droit décès': ['Art. 101'],
  'six mois décès': ['Art. 101'],
  'école privée': ['Art. 34 ter'],
  'abattement école': ['Art. 34 ter'],
  'établissement enseignement': ['Art. 34 ter'],
  'bons caisse précompte 15': ['Art. 61'],
  'bons caisse précompte': ['Art. 61'],
  'bons caisse declaration': ['Art. 61'],
  'bons caisse irpp': ['Art. 61'],
  'bons de caisse précompte': ['Art. 61'],
  'bons de caisse 15%': ['Art. 61'],
  'bons de caisse declaration irpp': ['Art. 61'],
  'précompte libératoire bons': ['Art. 61'],
  'précompte libératoire': ['Art. 61'],
  'précompte 15%': ['Art. 61'],
  'revenus bons caisse déclaration': ['Art. 61'],
  'bons nominatifs précompte': ['Art. 61'],
  'bons caisse doit declarer': ['Art. 61'],
  'declarer bons caisse': ['Art. 61'],
  'bons de caisse': ['Art. 61'],
  'impôt libératoire bons': ['Art. 61'],
  'gérant majoritaire': ['Art. 76'],
  'rémunération gérant': ['Art. 76'],
  'gérant sarl': ['Art. 76'],
  'organisation internationale': ['Art. 90'],
  'fonctionnaire international': ['Art. 90'],

  // ========== IS 2025 (Art. 106-126 septies) - Ancien chapitre IS ==========
  'principe is': ['Art. 106'],
  'definition is': ['Art. 106'],
  'cycle commercial': ['Art. 108'],
  'gerants majoritaires': ['Art. 110-A'],
  '20% frais siege': ['Art. 111'],
  'remunerations etranger': ['Art. 111'],
  '2% btp': ['Art. 111-A'],
  '5% commissions': ['Art. 111-B'],
  'locations': ['Art. 112'],
  '0,5 pour mille': ['Art. 113'],
  'credit-bail amortissement': ['Art. 114-D', 'Art. 114-E'],
  'ventes imposables': ['Art. 116'],
  'degrevements': ['Art. 116-B'],
  'ecarts conversion': ['Art. 116-C'],
  'peps': ['Art. 117'],
  'fifo': ['Art. 117'],
  'cout moyen pondere': ['Art. 117'],
  '3 ans deficit': ['Art. 119'],
  'exercice comptable': ['Art. 121'],
  '12 mois': ['Art. 121'],
  'premier bilan': ['Art. 121'],
  'calcul is': ['Art. 122'],
  'etablissement is': ['Art. 123'],
  'dissolution': ['Art. 123'],
  'fusion is': ['Art. 123'],
  'declaration existence': ['Art. 124'],
  'societes nouvelles': ['Art. 125'],

  // ========== DISPOSITIONS COMMUNES (Art. 127-140 bis) ==========
  'revision bilans': ['Art. 127'],
  'reevaluation': ['Art. 127'],
  'reevaluation bilans': ['Art. 127'],
  'plus-values reevaluation': ['Art. 127'],
  '31 decembre 1964': ['Art. 127'],
  'regimes derogatoires': ['Art. 127 quinquies'],
  'cpp': ['Art. 127 quinquies'],
  'contrat partage production': ['Art. 127 quinquies'],
  'convention etablissement': ['Art. 127 quinquies'],
  'regime privilegie': ['Art. 127 quinquies'],
  '1er janvier 2021': ['Art. 127 quinquies'],
  'non cumul regimes': ['Art. 127 quinquies'],
  'provision reconstitution gisements': ['Art. 133'],
  'prg': ['Art. 133'],
  'provision miniere': ['Art. 133'],
  'provision petroliere': ['Art. 133', 'Art. 134'],
  'franchise impot': ['Art. 133'],
  'substances minerales concessibles': ['Art. 133'],
  'hydrocarbures': ['Art. 134'],
  'petrole': ['Art. 134'],
  'gaz naturel': ['Art. 134'],
  'petrole brut': ['Art. 134'],
  '27,5%': ['Art. 134'],
  '27.5%': ['Art. 134'],
  '27,50%': ['Art. 134'],
  '50% benefice': ['Art. 134'],
  'ventes produits marchands': ['Art. 134'],
  'benefice net imposable hydrocarbures': ['Art. 134'],
  'deficit hydrocarbures': ['Art. 134'],
  '5 exercices deficit': ['Art. 134'],
  'report deficit hydrocarbures': ['Art. 134'],
  'redevances minieres': ['Art. 134'],
  'subventions production': ['Art. 134'],
  'inscription bilan provision': ['Art. 135'],
  'passif bilan provision': ['Art. 135'],
  'rubrique speciale provision': ['Art. 135'],
  'dotations exercice': ['Art. 135'],
  'utilisation provision': ['Art. 136'],
  'delai 5 ans provision': ['Art. 136'],
  'emplois autorises provision': ['Art. 136'],
  'travaux recherche hydrocarbures': ['Art. 136'],
  'immobilisations recherche': ['Art. 136'],
  'participations societes recherche': ['Art. 136'],
  'gisement reconnu': ['Art. 136'],
  'titre exploitation': ['Art. 136'],
  'remploi conforme': ['Art. 137'],
  'exoneration definitive': ['Art. 137'],
  'virement reserve': ['Art. 137'],
  'defaut remploi': ['Art. 137'],
  'imposition complementaire': ['Art. 137'],
  'sanction provision': ['Art. 137'],
  'cession entreprise provision': ['Art. 138'],
  'cessation activite provision': ['Art. 138'],
  'fusion provision': ['Art. 138'],
  'deces exploitant provision': ['Art. 138'],
  'heritiers provision': ['Art. 138'],
  'continuation exploitation': ['Art. 138'],
  'societe absorbante': ['Art. 138'],
  'obligations declaratives hydrocarbures': ['Art. 139'],
  'renseignements provision': ['Art. 139'],
  'declaration resultats hydrocarbures': ['Art. 139'],
  'substances minerales': ['Art. 140'],
  'minerais': ['Art. 140'],
  'mines': ['Art. 140'],
  'metaux': ['Art. 140'],
  'or': ['Art. 140'],
  'fer': ['Art. 140'],
  'cuivre': ['Art. 140'],
  'mattes': ['Art. 140'],
  'speiss': ['Art. 140'],
  'alliages': ['Art. 140'],
  '15% provision': ['Art. 140'],
  'provision 15%': ['Art. 140'],
  'gisements existants': ['Art. 140'],
  'mise en exploitation': ['Art. 140'],
  'amelioration recuperation': ['Art. 140'],
  'non cumul provisions': ['Art. 140 bis'],
  'reductions investissement': ['Art. 140 bis'],
  'cumul avantages': ['Art. 140 bis'],

  // ========== TAXES DIVERSES (Art. 157-171 L) ==========
  'taxes terrains': ['Art. 157'],
  'taxe terrain': ['Art. 157'],
  'terrain agrement': ['Art. 157', 'Art. 159'],
  'terrain non mis en valeur': ['Art. 157', 'Art. 159'],
  'terrain insuffisamment mis en valeur': ['Art. 159'],
  'terrain a batir': ['Art. 157', 'Art. 159'],
  'terrain inexploite': ['Art. 157', 'Art. 160'],
  'terrain insuffisamment exploite': ['Art. 160'],
  '5 fois superficie': ['Art. 159'],
  'jachere': ['Art. 160'],
  '3 ans plantation': ['Art. 160'],
  '51% superficie': ['Art. 160'],
  'brazzaville terrain': ['Art. 158'],
  'pointe-noire terrain': ['Art. 158'],
  'loudima': ['Art. 158'],
  'loubomo terrain': ['Art. 158', 'Art. 165'],
  'terrains urbains': ['Art. 158'],
  'exemption terrain': ['Art. 161'],
  'exemption temporaire terrain': ['Art. 162'],
  'lotissement': ['Art. 161'],
  'voie carrossable': ['Art. 161'],
  '100 metres': ['Art. 161'],
  'programme investissement terrain': ['Art. 162'],
  '25% majoration terrain': ['Art. 162'],
  'redevable terrain': ['Art. 163'],
  'proprietaire terrain': ['Art. 163'],
  'usufruitier': ['Art. 163'],
  'emphyteote': ['Art. 163'],
  '1er janvier terrain': ['Art. 164'],
  'fait generateur terrain': ['Art. 164'],
  'tarif terrain': ['Art. 165'],
  '15 f/m2': ['Art. 165'],
  '5 f/m2': ['Art. 165'],
  '40 f/m2': ['Art. 165'],
  '30 f/m2': ['Art. 165'],
  '20 f/m2': ['Art. 165'],
  '10 f/m2': ['Art. 165'],
  '250 f/ha': ['Art. 165'],
  'terrain marecageux': ['Art. 165'],
  'classes terrain': ['Art. 165'],
  '500 fcfa minimum terrain': ['Art. 165'],
  'declaration terrain': ['Art. 166'],
  '1er avril terrain': ['Art. 166'],
  'titre provisoire': ['Art. 167'],
  'titre definitif': ['Art. 167'],
  'exoneration titre': ['Art. 167 bis'],
  'tss': ['Art. 168'],
  'taxe speciale societes': ['Art. 168'],
  'minimum fiscal societes': ['Art. 168'],
  'minimum imposition societes': ['Art. 168'],
  'sa tss': ['Art. 168'],
  'sarl tss': ['Art. 168'],
  'sca': ['Art. 168'],
  'exoneration tss': ['Art. 169'],
  'agriculture tss': ['Art. 169'],
  'peche tss': ['Art. 169'],
  'elevage tss': ['Art. 169'],
  'premier exercice tss': ['Art. 169'],
  'taux tss': ['Art. 170'],
  '1% tss': ['Art. 170'],
  '2% tss': ['Art. 170'],
  'deficitaire tss': ['Art. 170'],
  '2 exercices consecutifs': ['Art. 170'],
  'minimum tss': ['Art. 170'],
  '1 000 000 fcfa tss': ['Art. 170'],
  '500 000 fcfa tss': ['Art. 170'],
  '10 000 000 fcfa ca': ['Art. 170'],
  'societes forestieres': ['Art. 170'],
  'marketeurs petroliers': ['Art. 170'],
  'marge distribution': ['Art. 170'],
  'paiement tss': ['Art. 171'],
  '10-20 mars': ['Art. 171'],
  'imputation tss': ['Art. 171'],
  'deduction is tss': ['Art. 171'],
  'doublement tss': ['Art. 171'],
  'sanction tss': ['Art. 171'],
  'bons caisse declaration irpp': ['Art. 61'],
  'precompte 15% bons': ['Art. 61'],
  'precompte liberatoire bons': ['Art. 61'],
  'declaration irpp bons': ['Art. 61', 'Art. 50', 'Art. 58'],
  'bons caisse liberatoire': ['Art. 61', 'Art. 97'],
  'taxe apprentissage': ['Art. 141'],
  'tus': ['Art. 141'],
  'taxe unique salaires': ['Art. 141'],

  // ========== DISPOSITIONS DIVERSES (Art. 172-185 ter-F) ==========
  'ras': ['Art. 172', 'Art. 183', 'Art. 185 ter-A'],
  'withholding': ['Art. 172', 'Art. 185 ter-A'],
  'employeur': ['Art. 172', 'Art. 173', 'Art. 174', 'Art. 176'],
  'employeurs': ['Art. 172', 'Art. 173', 'Art. 174'],
  'débirentier': ['Art. 172', 'Art. 173'],
  'débirentiers': ['Art. 172', 'Art. 173'],
  'prélèvement irpp': ['Art. 172'],
  'prélèvement salarié': ['Art. 172'],
  'versement retenue': ['Art. 173'],
  'versement retenues': ['Art. 173'],
  'versement mensuel': ['Art. 173'],
  'versement trimestriel': ['Art. 173'],
  '20 jours': ['Art. 173', 'Art. 183'],
  'vingt jours': ['Art. 173'],
  'mois suivant': ['Art. 173', 'Art. 183', 'Art. 183 bis'],
  '5 personnes': ['Art. 173'],
  'cinq personnes': ['Art. 173'],
  'trimestre': ['Art. 173'],
  'recette impôts': ['Art. 173'],
  'livre paie': ['Art. 174'],
  'livre de paie': ['Art. 174'],
  'registre paie': ['Art. 174'],
  'avantages nature': ['Art. 174', 'Art. 176'],
  'bordereau versement': ['Art. 174'],
  'enfants charge': ['Art. 174', 'Art. 176'],
  '4 ans': ['Art. 174'],
  'quatre ans': ['Art. 174'],
  'décès employeur': ['Art. 175'],
  'cessation employeur': ['Art. 175', 'Art. 181'],
  '15 jours': ['Art. 175', 'Art. 183 ter'],
  'état annuel': ['Art. 176', 'Art. 180'],
  'état annuel salaires': ['Art. 176'],
  'déclaration annuelle salaires': ['Art. 176'],
  'janvier': ['Art. 176', 'Art. 180'],
  '120000': ['Art. 176'],
  '120 000': ['Art. 176'],
  'déclaration nominative': ['Art. 176'],
  'récapitulatif annuel': ['Art. 176'],
  'niu': ['Art. 176'],
  'numéro identification': ['Art. 176'],
  '3 personnes': ['Art. 177'],
  'trois personnes': ['Art. 177'],
  'plus 3 personnes': ['Art. 177'],
  'déclaration mensuelle': ['Art. 177'],
  'fiche individuelle': ['Art. 177 bis'],
  'fiche salarié': ['Art. 177 bis'],
  'cession': ['Art. 178', 'Art. 181'],
  '6 mois': ['Art. 178'],
  'six mois': ['Art. 178'],
  '31 janvier': ['Art. 178'],
  'rémunérations diverses': ['Art. 179'],
  'jetons présence': ['Art. 179'],
  'allocations forfaitaires': ['Art. 179'],
  'remboursement frais': ['Art. 179'],
  '5000': ['Art. 179', 'Art. 183 bis'],
  '5 000': ['Art. 179', 'Art. 183 bis'],
  'état global': ['Art. 180'],
  'montant global': ['Art. 180'],
  'régularisation': ['Art. 181'],
  '10 jours': ['Art. 181'],
  'dix jours': ['Art. 181'],
  'trop perçu': ['Art. 181', 'Art. 182'],
  'réclamation': ['Art. 182'],
  '1er avril': ['Art. 182'],
  'premier avril': ['Art. 182'],
  'restitution': ['Art. 182'],
  'retenue 10': ['Art. 183', 'Art. 185 ter-C'],
  'retenue 10%': ['Art. 183'],
  '10 pourcent': ['Art. 183'],
  'courtages': ['Art. 183'],
  'ristournes': ['Art. 183'],
  'droits auteur': ['Art. 183', 'Art. 183 bis'],
  'vacations': ['Art. 183'],
  'gratifications': ['Art. 183'],
  'rémunérations occasionnelles': ['Art. 183'],
  'prestations occasionnelles': ['Art. 183'],
  'défaut retenue': ['Art. 183'],
  'défaut reversement': ['Art. 183'],
  'amende retenue': ['Art. 183'],
  'intérêt 5%': ['Art. 183'],
  '5% mois': ['Art. 183'],
  'manifestations': ['Art. 183 bis'],
  'représentations': ['Art. 183 bis'],
  'auteurs': ['Art. 183 bis', 'Art. 183'],
  'compositeurs': ['Art. 183 bis'],
  'commissionnaires douanes': ['Art. 183 ter'],
  'commissionnaire douane': ['Art. 183 ter'],
  'transitaires': ['Art. 183 ter'],
  'déclarant douane': ['Art. 183 ter'],
  'avant 15': ['Art. 183 ter'],
  '500000': ['Art. 183 ter'],
  '500 000': ['Art. 183 ter'],
  'amende 500000': ['Art. 183 ter'],
  'société nom collectif': ['Art. 184'],
  'commandite simple': ['Art. 184'],
  'associés gérants': ['Art. 184'],
  'répartition bénéfices': ['Art. 184'],
  'parts bénéfices': ['Art. 184'],
  'résultat fiscal': ['Art. 184'],
  'source étrangère': ['Art. 185'],
  'revenus étrangers': ['Art. 185'],
  'revenus étranger': ['Art. 185'],
  'pensions étrangères': ['Art. 185'],
  'salaires étrangers': ['Art. 185'],
  'renseignements source': ['Art. 185'],
  '126 ter': ['Art. 185 bis'],
  'article 126 ter': ['Art. 185 bis'],
  'sociétés étrangères pétrolières': ['Art. 185 bis'],
  'sous-traitants pétroliers': ['Art. 185 bis'],
  'sous-traitant pétrolier': ['Art. 185 bis'],
  'prestataires pétroliers': ['Art. 185 bis'],
  'régime 126 ter': ['Art. 185 bis'],
  'liste salariés': ['Art. 185 bis'],
  'non-résidents': ['Art. 185 ter-A', 'Art. 185 ter-B', 'Art. 185 ter-C'],
  'non résidents': ['Art. 185 ter-A', 'Art. 185 ter-B', 'Art. 185 ter-C'],
  'non-résident': ['Art. 185 ter-A', 'Art. 185 ter-C'],
  'sans domicile fiscal': ['Art. 185 ter-A'],
  'personnes étrangères': ['Art. 185 ter-A'],
  'royalties': ['Art. 185 ter-A', 'Art. 185 ter-C'],
  'marques': ['Art. 185 ter-A'],
  'procédés secrets': ['Art. 185 ter-A'],
  'know-how': ['Art. 185 ter-A'],
  'assistance technique': ['Art. 185 ter-A'],
  'assistance financière': ['Art. 185 ter-A'],
  'assistance comptable': ['Art. 185 ter-A'],
  'location équipements': ['Art. 185 ter-A'],
  'location matériel': ['Art. 185 ter-A'],
  'trading': ['Art. 185 ter-A'],
  'commercialisation hydrocarbures': ['Art. 185 ter-A'],
  'frais commercialisation': ['Art. 185 ter-A'],
  'propriété intellectuelle': ['Art. 185 ter-A'],
  'débiteur résident': ['Art. 185 ter-B'],
  'payeur résident': ['Art. 185 ter-B'],
  'obligation retenue non-résident': ['Art. 185 ter-B'],
  'taux non-résidents': ['Art. 185 ter-C'],
  'taux retenue non-résidents': ['Art. 185 ter-C'],
  '20%': ['Art. 185 ter-C'],
  '20 pourcent': ['Art. 185 ter-C'],
  'vingt pourcent': ['Art. 185 ter-C'],
  'taux général': ['Art. 185 ter-C'],
  'prestations ponctuelles': ['Art. 185 ter-C'],
  'redevances audiovisuelles': ['Art. 185 ter-C'],
  'streaming': ['Art. 185 ter-C'],
  'cemac': ['Art. 185 ter-C'],
  'résidents cemac': ['Art. 185 ter-C'],
  '5,75%': ['Art. 185 ter-C'],
  'affrètement': ['Art. 185 ter-C'],
  'location navires': ['Art. 185 ter-C'],
  'location aéronefs': ['Art. 185 ter-C'],
  'transport maritime': ['Art. 185 ter-C'],
  'transport aérien': ['Art. 185 ter-C'],
  'agents portuaires': ['Art. 185 ter-C'],
  'cinq pourcent': ['Art. 185 ter-C'],
  'emprunts pétroliers': ['Art. 185 ter-C'],
  'exploration pétrolière': ['Art. 185 ter-C'],
  'exploitation pétrolière': ['Art. 185 ter-C'],
  'imputation retenue': ['Art. 185 ter-D'],
  'crédit impôt': ['Art. 185 ter-D'],
  'déduction retenue': ['Art. 185 ter-D'],
  'procédure versement': ['Art. 185 ter-E'],
  'modalités versement': ['Art. 185 ter-E'],
  'exclusions non-résidents': ['Art. 185 ter-F'],
  'exonération non-résidents': ['Art. 185 ter-F'],
  'dérogation retenue': ['Art. 185 ter-F'],

  // ========== PLUS-VALUES SUR TITRES, BTP, RÉASSURANCE (Art. 185 quater-sexies) ==========
  'plus-value': ['Art. 185 quater-A', 'Art. 185 quater-B'],
  'plus values': ['Art. 185 quater-A', 'Art. 185 quater-B'],
  'gains capital': ['Art. 185 quater-A'],
  'gains en capital': ['Art. 185 quater-A'],
  'cession titres': ['Art. 185 quater-A', 'Art. 185 quater-B'],
  'cession participations': ['Art. 185 quater-A'],
  'vente actions': ['Art. 185 quater-A'],
  'vente titres': ['Art. 185 quater-A'],
  'sociétés congolaises': ['Art. 185 quater-A', 'Art. 185 quater-C'],
  'société droit congolais': ['Art. 185 quater-A', 'Art. 185 quater-C'],
  'domiciliés étranger': ['Art. 185 quater-A'],
  'impôt spécial': ['Art. 185 quater-A', 'Art. 185 quater-B'],
  '20% plus-values': ['Art. 185 quater-B'],
  'taux 20%': ['Art. 185 quater-B', 'Art. 185 sexies'],
  'enregistrement cession': ['Art. 185 quater-B'],
  'droits enregistrement': ['Art. 185 quater-B'],
  'acte cession': ['Art. 185 quater-B'],
  'solidarité paiement': ['Art. 185 quater-C'],
  'solidairement responsables': ['Art. 185 quater-C'],
  'cédant': ['Art. 185 quater-C'],
  'cessionnaire': ['Art. 185 quater-C'],
  'responsables solidaires': ['Art. 185 quater-C'],
  'btp': ['Art. 185 quinquies'],
  'batiments travaux publics': ['Art. 185 quinquies'],
  'bâtiments travaux publics': ['Art. 185 quinquies'],
  'construction': ['Art. 185 quinquies'],
  'travaux publics': ['Art. 185 quinquies'],
  'sous-traitants': ['Art. 185 quinquies'],
  'sous-traitant': ['Art. 185 quinquies'],
  'sous-traitance': ['Art. 185 quinquies'],
  'bureaux études': ['Art. 185 quinquies'],
  "bureaux d'études": ['Art. 185 quinquies'],
  'entrepreneur principal': ['Art. 185 quinquies'],
  'adjudicataires': ['Art. 185 quinquies'],
  'marchés publics': ['Art. 185 quinquies'],
  'marchés privés': ['Art. 185 quinquies'],
  'marchés construction': ['Art. 185 quinquies'],
  '3%': ['Art. 185 quinquies'],
  'trois pourcent': ['Art. 185 quinquies'],
  '10% btp': ['Art. 185 quinquies'],
  'retenue btp': ['Art. 185 quinquies'],
  'retenue sous-traitants': ['Art. 185 quinquies'],
  'acompte impôt': ['Art. 185 quinquies'],
  'déclaration trimestrielle': ['Art. 185 quinquies'],
  'liste sous-traitants': ['Art. 185 quinquies'],
  'bordereau spécial': ['Art. 185 quinquies'],
  'enregistrement marché': ['Art. 185 quinquies'],
  'enregistrement contrat': ['Art. 185 quinquies'],
  '5000000': ['Art. 185 quinquies'],
  '5 000 000': ['Art. 185 quinquies'],
  'amende btp': ['Art. 185 quinquies'],
  'perte déductibilité': ['Art. 185 quinquies'],
  '2% mois': ['Art. 185 quinquies'],
  'pénalité retard': ['Art. 185 quinquies'],
  'réassurance': ['Art. 185 sexies'],
  'reassurance': ['Art. 185 sexies'],
  'primes cédées': ['Art. 185 sexies'],
  'primes réassurance': ['Art. 185 sexies'],
  'cima': ['Art. 185 sexies'],
  'code cima': ['Art. 185 sexies'],
  'art. 308 cima': ['Art. 185 sexies'],
  'article 308': ['Art. 185 sexies'],
  'hors cima': ['Art. 185 sexies'],
  'assurance étranger': ['Art. 185 sexies'],
  'plafond réassurance': ['Art. 185 sexies'],
  '20% réassurance': ['Art. 185 sexies'],
  'retenue réassurance': ['Art. 185 sexies'],
  'autorisation ministre': ['Art. 185 sexies'],
  'ministre assurances': ['Art. 185 sexies'],

  // ========== IMPÔTS LOCAUX (Art. 250-340 bis) ==========
  // Généralités
  'impôts locaux': ['Art. 250'],
  'impots locaux': ['Art. 250'],
  'répartition impôts': ['Art. 250'],
  '85%': ['Art. 250'],
  '85% collectivités': ['Art. 250'],
  '10% administration': ['Art. 250'],
  '5% chambres commerce': ['Art. 250'],
  'collectivités locales': ['Art. 250'],
  'chambres de commerce': ['Art. 250'],

  // CFPB - Contribution Foncière Propriétés Bâties (Art. 251-262)
  'cfpb': ['Art. 251', 'Art. 252', 'Art. 257', 'Art. 258 ter'],
  'contribution foncière propriétés bâties': ['Art. 251', 'Art. 252'],
  'foncier bâti': ['Art. 251', 'Art. 257'],
  'impôt foncier bâti': ['Art. 251', 'Art. 258 ter'],
  'constructions': ['Art. 251', 'Art. 253'],
  'bâtiments': ['Art. 251', 'Art. 253'],
  'immeubles': ['Art. 251', 'Art. 252'],
  'propriétaire': ['Art. 252'],
  'usufruit': ['Art. 252'],
  'redevable cfpb': ['Art. 252'],
  'exemption cfpb': ['Art. 253', 'Art. 254'],
  'exonération cfpb': ['Art. 253', 'Art. 254'],
  'exemptions permanentes': ['Art. 253'],
  'exemptions temporaires': ['Art. 254'],
  'édifices culte': ['Art. 253'],
  'bâtiments agricoles': ['Art. 253'],
  'granges': ['Art. 253'],
  'hangars': ['Art. 253'],
  'écuries': ['Art. 253'],
  'ambassades': ['Art. 253'],
  'défense passive': ['Art. 253'],
  'constructions nouvelles': ['Art. 254'],
  '5 ans exemption': ['Art. 254'],
  '10 ans exemption': ['Art. 254'],
  '25 ans exemption': ['Art. 254'],
  'habitation principale': ['Art. 254'],
  'logement personnel': ['Art. 254'],
  'valeur locative': ['Art. 257', 'Art. 257 bis', 'Art. 276'],
  'valeur locative cadastrale': ['Art. 257'],
  'revenu cadastral': ['Art. 257'],
  '75% déduction': ['Art. 257'],
  'déduction 75%': ['Art. 257'],
  'frais gestion': ['Art. 257'],
  'frais entretien': ['Art. 257'],
  'zones tarifaires': ['Art. 258', 'Art. 258 bis', 'Art. 270'],
  'zone 1': ['Art. 258', 'Art. 270'],
  'zone 2': ['Art. 258', 'Art. 270'],
  'zone 3': ['Art. 258', 'Art. 270'],
  'zone 4': ['Art. 258', 'Art. 270'],
  '250 fcfa': ['Art. 258'],
  '150 fcfa': ['Art. 258'],
  '25 fcfa': ['Art. 258'],
  '12,5 fcfa': ['Art. 258'],
  'prix m2': ['Art. 258', 'Art. 270'],
  'prix mètre carré': ['Art. 258'],
  'centre-ville': ['Art. 258', 'Art. 270'],
  'communes plein exercice': ['Art. 258'],
  'chefs-lieux départements': ['Art. 258'],
  'chefs-lieux districts': ['Art. 258'],
  'réduction étage': ['Art. 258 bis'],
  '50% par étage': ['Art. 258 bis'],
  'taux cfpb': ['Art. 258 ter'],
  '20% cfpb': ['Art. 258 ter'],
  'taux maximum cfpb': ['Art. 258 ter'],
  '1000 fcfa minimum': ['Art. 258 ter', 'Art. 272'],
  'déclaration cfpb': ['Art. 260', 'Art. 261'],
  'fait générateur': ['Art. 260'],
  '1er janvier': ['Art. 260'],
  'avis imposition': ['Art. 261', 'Art. 274'],
  'paiement cfpb': ['Art. 262'],

  // CFPNB - Contribution Foncière Propriétés Non Bâties (Art. 263-275)
  'cfpnb': ['Art. 263', 'Art. 264', 'Art. 270', 'Art. 272'],
  'contribution foncière propriétés non bâties': ['Art. 263', 'Art. 264'],
  'propriétés non bâties': ['Art. 263', 'Art. 264', 'Art. 265'],
  'foncier non bâti': ['Art. 263', 'Art. 270'],
  'impôt foncier non bâti': ['Art. 263', 'Art. 272'],
  'terrains': ['Art. 263', 'Art. 264'],
  'terrains ruraux': ['Art. 264', 'Art. 270 bis'],
  'sols': ['Art. 263'],
  'périmètre urbain': ['Art. 264'],
  'exemption cfpnb': ['Art. 265', 'Art. 266'],
  'exonération cfpnb': ['Art. 265', 'Art. 266'],
  'propriétés état': ['Art. 265'],
  'voies ferrées': ['Art. 265'],
  'canaux navigation': ['Art. 265'],
  'cimetières': ['Art. 265'],
  'cultures maraîchères': ['Art. 266'],
  '5 hectares': ['Art. 266'],
  '25 km agglomération': ['Art. 266'],
  'plantations nouvelles': ['Art. 266'],
  '6 ans élevage': ['Art. 266'],
  'hévéas': ['Art. 266'],
  'palmiers': ['Art. 266', 'Art. 270 bis'],
  '10 ans palmiers': ['Art. 266'],
  'arbres fruitiers': ['Art. 266'],
  '8 ans fruitiers': ['Art. 266'],
  'café cacao': ['Art. 266'],
  '7 ans café': ['Art. 266'],
  '3 ans cultures': ['Art. 266'],
  'déclaration cfpnb': ['Art. 267', 'Art. 268'],
  'avant 1er octobre': ['Art. 267', 'Art. 276'],
  'valeur cadastrale': ['Art. 270'],
  '50% base': ['Art. 270'],
  'base 50%': ['Art. 270'],
  '125 fcfa': ['Art. 270'],
  '75 fcfa': ['Art. 270'],
  '6,25 fcfa': ['Art. 270'],
  'tarifs ruraux': ['Art. 270 bis'],
  'tarif hectare': ['Art. 270 bis'],
  '2000 fcfa/ha': ['Art. 270 bis'],
  '1000 fcfa/ha': ['Art. 270 bis'],
  '600 fcfa/ha': ['Art. 270 bis'],
  'caféiers': ['Art. 270 bis'],
  'caoutchouc': ['Art. 270 bis'],
  'forêts': ['Art. 270 bis'],
  'non mis en valeur': ['Art. 270 bis'],
  'taux cfpnb': ['Art. 272'],
  '40% cfpnb': ['Art. 272'],
  'taux maximum cfpnb': ['Art. 272'],
  'paiement cfpnb': ['Art. 275'],
  'déclaration locataires': ['Art. 276'],

  // CONTRIBUTION DES PATENTES (Art. 277-314)
  'patente': ['Art. 277', 'Art. 278', 'Art. 314'],
  'contribution patentes': ['Art. 277'],
  'droit patente': ['Art. 277'],
  'activité commerciale': ['Art. 277'],
  'activité industrielle': ['Art. 277'],
  'profession': ['Art. 277'],
  'chiffre affaires patente': ['Art. 278'],
  'ca patente': ['Art. 278'],
  'assiette patente': ['Art. 278'],
  'exemption patente': ['Art. 279'],
  'exonération patente': ['Art. 279'],
  'peintres': ['Art. 279'],
  'sculpteurs': ['Art. 279'],
  'graveurs': ['Art. 279'],
  'pêcheurs': ['Art. 279'],
  'piroguiers': ['Art. 279'],
  'caisses épargne': ['Art. 279'],
  'mutuelles': ['Art. 279'],
  'ouvriers': ['Art. 279'],
  'couturiers': ['Art. 279'],
  'économats': ['Art. 279'],
  'coopératives': ['Art. 279'],
  'entité fiscale': ['Art. 281'],
  'établissement': ['Art. 281'],
  'succursale': ['Art. 281'],
  'titre patente': ['Art. 282'],
  'affichage patente': ['Art. 285'],
  'début activité': ['Art. 287'],
  'cessation activité': ['Art. 289'],
  'transfert établissement': ['Art. 290'],
  'annuité patente': ['Art. 287'],
  'sociétés étrangères': ['Art. 294'],
  'marchés publics sociétés': ['Art. 294'],
  '15 jours début activité': ['Art. 294'],
  'patente provisoire': ['Art. 294'],
  'ambulants': ['Art. 295'],
  'marchands ambulants': ['Art. 295'],
  'forains': ['Art. 295'],
  'transporteurs': ['Art. 296'],
  'transporteurs fluviaux': ['Art. 296'],
  'sociétés pétrolières': ['Art. 297'],
  '50% droits': ['Art. 297'],
  'matrices patente': ['Art. 301', 'Art. 302'],
  'rôle patente': ['Art. 303'],
  'titre perception': ['Art. 304'],
  'paiement patente': ['Art. 305'],
  '10-20 avril': ['Art. 305'],
  'paiement fractionné': ['Art. 305'],
  '100 000 fcfa': ['Art. 305'],
  'retard paiement patente': ['Art. 306'],
  '100% pénalité': ['Art. 306'],
  'stand-by': ['Art. 307'],
  'stand by': ['Art. 307'],
  '25% stand-by': ['Art. 307'],
  'activité intermittente': ['Art. 307'],
  'déclaration patente': ['Art. 308', 'Art. 309', 'Art. 312'],
  'contrôle patente': ['Art. 310'],
  'entrepôt': ['Art. 311'],
  '500 000 fcfa amende': ['Art. 311'],
  'déclaration ca': ['Art. 312'],
  '30 avril': ['Art. 312'],
  'sanctions patente': ['Art. 313'],
  'barème patente': ['Art. 314'],
  'tarif patente': ['Art. 314'],
  'taux patente': ['Art. 314'],
  '0,750%': ['Art. 314'],
  '0,650%': ['Art. 314'],
  '0,450%': ['Art. 314'],
  '0,200%': ['Art. 314'],
  '0,150%': ['Art. 314'],
  '0,140%': ['Art. 314'],
  '0,135%': ['Art. 314'],
  '0,125%': ['Art. 314'],
  '0,045%': ['Art. 314'],
  '10 000 fcfa minimum': ['Art. 314'],
  'minimum forfaitaire': ['Art. 314'],
  'progressif patente': ['Art. 314'],
  '20 millions': ['Art. 314'],
  '40 millions': ['Art. 314'],
  '300 millions': ['Art. 314'],
  '500 millions': ['Art. 314'],
  '1 milliard': ['Art. 314'],
  '3 milliards': ['Art. 314'],
  '20 milliards': ['Art. 314'],

  // TAXE RÉGIONALE (Art. 321-327)
  'taxe régionale': ['Art. 321', 'Art. 322', 'Art. 326'],
  'taxe regionale': ['Art. 321', 'Art. 322'],
  'personnes physiques': ['Art. 321'],
  '18 ans': ['Art. 321'],
  'âge minimum': ['Art. 321'],
  'résidence': ['Art. 322'],
  'exemption taxe régionale': ['Art. 323'],
  'aveugles': ['Art. 323'],
  'mutilés guerre': ['Art. 323'],
  'indigents': ['Art. 323'],
  'recouvrement taxe régionale': ['Art. 324'],
  'rôle nominatif': ['Art. 324'],
  '120 000 fcfa': ['Art. 324'],
  'précompte employeur': ['Art. 325'],
  'précompte janvier': ['Art. 325'],
  'tarif taxe régionale': ['Art. 326'],
  'paiement taxe régionale': ['Art. 327'],

  // TAXE SUR LES SPECTACLES (Art. 331-340 bis)
  'taxe spectacles': ['Art. 331', 'Art. 333'],
  'taxe sur les spectacles': ['Art. 331'],
  'jeux': ['Art. 331'],
  'divertissements': ['Art. 331'],
  'exemption spectacles': ['Art. 332'],
  'manifestations sportives': ['Art. 332'],
  'spectacles éducatifs': ['Art. 332'],
  'fêtes patronales': ['Art. 332'],
  'tarif spectacles': ['Art. 333'],
  '15%': ['Art. 333'],
  '200 fcfa entrée': ['Art. 333'],
  'bar dancing': ['Art. 334'],
  'bars dancings': ['Art. 334'],
  'bar-dancing': ['Art. 334'],
  'dancing': ['Art. 334'],
  'musiciens': ['Art. 334'],
  'pick-up': ['Art. 334'],
  'pickup': ['Art. 334'],
  '240 000 fcfa': ['Art. 334'],
  '100 000 fcfa pickup': ['Art. 334'],
  '120 000 fcfa non permanent': ['Art. 334'],
  '50 000 fcfa': ['Art. 334'],
  'permanent': ['Art. 334'],
  'non permanent': ['Art. 334'],
  'salle bal': ['Art. 335'],
  '4 000 fcfa bal': ['Art. 335'],
  'cercles privés': ['Art. 336'],
  '10% recettes': ['Art. 336'],
  'appareils jeux': ['Art. 337'],
  'baby-foot': ['Art. 337'],
  'billard': ['Art. 337'],
  'déclaration spectacles': ['Art. 340', 'Art. 340 bis'],
  '24h avant': ['Art. 340'],
  'relevé recettes': ['Art. 340'],
  '15 jours du mois': ['Art. 340'],
  'spectacle occasionnel': ['Art. 340'],
  '3 jours après': ['Art. 340'],
  'billets entrée': ['Art. 338'],
  'tickets spectacles': ['Art. 338'],
  'paiement spectacles': ['Art. 339'],
};

/**
 * Synonymes pour expansion de requetes CGI 2026
 */
export const SYNONYMS_2026: Record<string, string[]> = {
  'is': ['impot sur les societes', 'impot societes', 'corporate tax'],
  'minimum de perception': ['minimum is', 'impot minimum', 'plancher fiscal'],
  'holding': ['societe de participation', 'societe portefeuille'],
  'amortissement': ['dotation aux amortissements', 'depreciation', 'dap'],
  'retenue a la source': ['ras', 'withholding tax', 'prelevement a la source', 'wht'],
  'dividendes': ['distributions', 'benefices distribues', 'irvm'],
  'sanctions': ['penalites', 'amendes', 'majorations'],
  'acomptes': ['versements anticipes', 'paiements fractionnaires'],
  'ebitda': ['ebe', 'excedent brut exploitation'],
  // Nouveaux synonymes pour tests 7, 21, 33, 88, 98, 99
  // IRF - Synonymes pour revenus fonciers
  'plus-values immobilieres': ['gains immobiliers', 'profit cession immobiliere', 'plus-value immeuble'],

  // Synonymes migrés depuis CGI 2025 - IS
  'deficit reportable': ['report deficitaire', 'pertes reportables'],
  'sous-traitant petrolier': ['contractor', 'prestataire petrolier'],

  // Synonymes migrés depuis CGI 2025 - Dispositions Communes
  'gisement': ['gite', 'reserves', 'ressources', 'depot'],
  'remploi': ['utilisation provision', 'affectation provision', 'emploi provision'],

  // Synonymes migrés depuis CGI 2025 - Taxes Diverses
  'exemption': ['exoneration', 'dispense', 'franchise'],
  'precompte 15%': ['retenue liberatoire', 'impot liberatoire bons'],

  // Synonymes migrés depuis CGI 2025 - Dispositions Diverses

  // Synonymes migrés depuis CGI 2025 - Plus-values, BTP, Réassurance

  // Synonymes migrés depuis CGI 2025 - Impôts Locaux
  'immeuble': ['propriété bâtie', 'construction', 'bâtiment'],
  'terrain': ['propriété non bâtie', 'sol', 'fonds de terre'],
};
