-- Ajout des AuditAction pour le suivi des modifications du catalogue
-- d'obligations, des entites fiscales et des dossiers (Bloc 1.1, 1.2, 2.x)

ALTER TYPE "AuditAction" ADD VALUE 'OBLIGATION_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'OBLIGATION_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'OBLIGATION_ACTIVATED';
ALTER TYPE "AuditAction" ADD VALUE 'OBLIGATION_DEACTIVATED';
ALTER TYPE "AuditAction" ADD VALUE 'OBLIGATIONS_VERSION_CLONED';

ALTER TYPE "AuditAction" ADD VALUE 'ENTITE_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'ENTITE_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'ENTITE_ACTIVATED';
ALTER TYPE "AuditAction" ADD VALUE 'ENTITE_DEACTIVATED';

ALTER TYPE "AuditAction" ADD VALUE 'DOSSIERS_RECALCULES';
ALTER TYPE "AuditAction" ADD VALUE 'DOSSIER_UPDATED';
